import type { Metadata } from 'next'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import React from 'react'
import { ToastProvider } from './components/ui/Toast'
import { useServiceWorker } from './lib/hooks'

const geistSans = Geist({
	variable: '--font-geist-sans',
	subsets: ['latin'],
})

const geistMono = Geist_Mono({
	variable: '--font-geist-mono',
	subsets: ['latin'],
})

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	manifest: "/manifest.json",
}

export default function RootLayout({
									   children,
								   }: Readonly<{
	children: React.ReactNode;
}>) {
	useServiceWorker()
	
	return (
		<html lang="fr">
		<body
			className={`${geistSans.variable} ${geistMono.variable} antialiased bg-peach-yellow`}
		>
		<ToastProvider>
			{children}
		</ToastProvider>
		</body>
		</html>
	)
}
